---
- hosts: vagrant
  become: yes

  roles:
    - vagrant

- hosts: database
  become: yes

  vars_files:
    - group_vars/all_vault.yml

  roles:
    - { role: mysql, tags: [mysql] }

- hosts: wordpress
  become: yes

  vars_files:
    - group_vars/all_vault.yml

  roles:
    - { role: predeploy, tags: [predeploy] }
    - { role: nginx, tags: [nginx] }
    - { role: wordpress, tags: [wordpress] }

- hosts: balancer
  become: yes

  vars_files:
    - group_vars/all_vault.yml

  roles:
    - { role: balancer, tags: [balancer] }
    