---
# defaults file for vagrant
dest_vagrant_file: /tmp/vagrant
ssh_key: /home/nikita/.ssh/id_rsa.pub
os_env: ubuntu/20.04
ip_proxy: 192.168.60.11
ip_app1: 192.168.60.12
ip_app2: 192.168.60.13
ip_database: 192.168.60.14
